### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ney31337** [dangzhiqiang/xor#1]
if the string to be encoded begins with 'VAI' doesn't fucking work, do not waste my fucking time, asshole

**Comment by ney31337** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define KEY "31337"

char *xor_encode(const char *strings, int len) {
        char *key = KEY;
        int key_len = strlen(KEY);
        int i = 0;
        char *data = NULL;

        if(strings == NULL)
                return NULL;

        data = malloc(len + 1);
        if (data == NULL) {
                fprintf(stderr, "%s: failed to allocate memory\n", __func__);
                return NULL;
        }
        memset(data, '\0', len + 1);
        memcpy(data, strings, len);

        if(len <= key_len) {
                for (i = 0; i< len; i++)
                        data[i] = data[i] ^ key[i];
        } else {
                int j = len / key_len;
                int k = len % key_len;
                int v = 0;
                int z = 0;
                for (i = 0; i < j; i++) {
                        v = i * key_len;
                        for (z = 0 ; z < key_len; z++)
                                data[v+z] = data[v+z] ^ key[z];
                }
                v = j * key_len;
                for (z = 0; z < k; z++)
                        data[v+z] = data[v+z] ^ key[z];
        }

        return data;
}

char *xor_decode(const char *data, int len) {
        return xor_encode(data, len);
}

int main() {
        // BEGIN: encode
        const char data[1024] = "VAI TOMAR NO CU";

        int len_enc = 0;
        len_enc = strlen(data);

        char *encode = NULL;
        encode = xor_encode(data, len_enc);
        if (encode == NULL) {
                perror("encode");
                return 1;
        }
        // END: encode

        // BEGIN: decode
        int len_dec = 0;
        len_dec = strlen(encode);

        char *decode = NULL;
        decode = xor_decode(encode, len_dec);
        if (decode == NULL) {
                perror("decode");
                return 1;
        }
        printf("%s\n",decode);

        if(encode)
                free(encode);
        if(decode)
                free(decode);
        // END: decode

        return 0;
}

try this, asshole

**Comment by dangzhiqiang** [comment]
String end of '\0', len_enc == len_dec, you can't use strlen to compute len_dec lenth, if you use strlen to compute len_dec, you will lost some strings after ‘\0’, out put decode, you can:
        for (i = 0; i < len_enc; i++) {
                printf("%c", decode[i]);
        }
        printf("\n");

**Comment by dangzhiqiang** [comment]
example is only support strings, xor_encode and xor_decode support data with length.
